DesiFood/Areas/Admin/Controllers/TestimonialController.cs
using CMS.Admin.Facade;
using CMS.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesiFood.Areas.Admin.Controllers
{
    public class TestimonialController : Controller
    {
        // GET: Admin/Testimonial
        TestimonialFacade _facade = new TestimonialFacade();
        
        public ActionResult Index()
        {
            var data = _facade.GetAllTestimonials();
            return View(data);
        }

        public ActionResult AddNew(long? tid)
        {
            if (tid != null)
            {
                var data = _facade.LoadTestimonial((long)tid);
                return View(data);
            }
            else
                return View();
        }

        [HttpPost]
        public JsonResult SaveList(TestimonialDto dto)
        {
            var data = _facade.SaveTestimonial(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult RemoveList(long tid)
        {
            var data = _facade.DeleteTestimonial(tid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(long tid)
        {
            var data = _facade.LoadTestimonial((long)tid);
            return View(data);
        }
    }
}

DesiFood/Areas/Admin/Views/Testimonial/AddNew.cshtml
@model CMS.Dto.TestimonialDto
@{
    ViewBag.Title = "Add New Testimonial";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Add Testimonial
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">
                                    @Html.ActionLink("All Testimonials", "Index", "Testimonial")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">Add New</li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form id="save_form">
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add Form</strong>
                        </div>
                        <div class="card-body card-block">

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Person, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.HiddenFor(model => model.Id)
                                    @Html.Hidden("TestimonialType",1)

                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.Person, new { @class = "form-control" })

                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "form-control-label" })
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.Designation, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Company, htmlAttributes: new { @class = "form-control-label" })
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.Company, new { @class = "form-control" })

                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Photo, "Thumbnail Image", htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @if (Model != null)
                                    {
                                        <img src="@Model.PhotoPath" width="25%" />
                                    }
                                    <input type="file" id="Photo" class="form-control-file">
                                    <small class="form-text text-muted">This is Thumb image</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.TestimonialText, htmlAttributes: new { @class = "form-control-label" })
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextAreaFor(model => model.TestimonialText, new { @class = "form-control" })

                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "form-control-label" })
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })

                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.SortIndex, "Sort Index", htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.SortIndex, new { @class = "form-control", @type = "number" })
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="button" id="btnSave" class="btn btn-primary btn-sm">
                                <i class="fa fa-dot-circle-o"></i> Submit
                            </button>

                        </div>
                    </div>

                </div>

            </form>

        </div>

        <div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="smallmodalLabel">Response</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p id="successModalText"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
<script>
    $('#btnSave').on('click', function () {
        //event.preventDefault();
        tinymce.triggerSave();
        $('#' + 'TestimonialText').html(tinymce.get('TestimonialText').getContent());
        var photoFile = $('#Photo').prop('files')[0];
        var form = document.getElementById('save_form');
        var form_data = new FormData(form);
        form_data.append('Photo', photoFile);
        $.ajax({
            type: "POST",
            url: '/Admin/Testimonial/SaveList',
            data: form_data,
            processData: false,
            contentType: false,
            success: function (data) {
                $('#successModal').modal('show');
                $('#successModalText').text(data.Message);

            },
            error: function () {
                $('#successModal').modal('show');
                $('#successModalText').text(error.status + "<--save and--> " + error.statusText);

            }
        });
    });
</script>

DesiFood/Areas/Admin/Views/Testimonial/Details.cshtml
@model CMS.Dto.TestimonialDto
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Testimonial Details
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">
                                    @Html.ActionLink("All Testimonials", "Index", "Testimonial")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">More Information</li>

                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <a href='@Url.Action("Index", "Testimonial")'>Back to List</a>
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form>
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Blog Details</strong>
                        </div>
                        <div class="card-body card-block">
                            <dl class="dl-horizontal">

                                <dt>
                                    @Html.DisplayName("Person")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Person)
                                </dd>


                                <dt>
                                    @Html.DisplayName("Designation")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Designation)
                                </dd>
                                <dt>
                                    @Html.DisplayName("Company")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CommentDate)
                                </dd>
                                <dt>
                                    @Html.DisplayName("Image")
                                </dt>

                                <dd>
                                    <img src="@Model.PhotoPath" alt="@Model.Person" width="25%">
                                </dd>
                                <dt>
                                    @Html.DisplayName("Company")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Company)
                                </dd>
                                <dt>
                                    @Html.DisplayName("Comment")
                                </dt>

                                <dd>
                                    @Html.Raw(HttpUtility.HtmlDecode(Model.TestimonialText))
                                </dd>
                                <dt>
                                    @Html.DisplayName("Email")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Email)
                                </dd>
                                <dt>
                                    @Html.DisplayName("Sort Index")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.SortIndex)
                                </dd>

                                <dt>
                                    @Html.DisplayName("Comment Date")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.CommentDateText)
                                </dd>


                            </dl>

                        </div>

                        <div class="card-footer">
                            <p>
                                <a href='@Url.Action("AddNew", "Testimonial",new { tid = Model.Id })'>Edit</a>  |  <a href='@Url.Action("Index", "Testimonial")'>Back to List</a>
                            </p>
                        </div>
                    </div>

                </div>

            </form>

        </div>

    </section>

</div>

DesiFood/Areas/Admin/Views/Testimonial/Index.cshtml
@model IEnumerable<CMS.Dto.TestimonialDto>
@{
    ViewBag.Title = "Testimonials";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}
    <div class="page-content--bgf7 main-content">

        <!-- END BREADCRUMB-->
        <!-- WELCOME-->
        <section class="welcome p-t-10">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="title-4">
                            All Testimonials
                        </h1>
                        <hr class="line-seprate">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="au-breadcrumb-content">
                            <div class="au-breadcrumb-left">
                                <span class="au-breadcrumb-span">You are here:</span>
                                <ul class="list-unstyled list-inline au-breadcrumb__list">
                                    <li class="list-inline-item active">
                                        <a href="#">Home</a>
                                    </li>
                                    <li class="list-inline-item seprate">
                                        <span>/</span>
                                    </li>
                                    <li class="list-inline-item">Testimonials</li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END WELCOME-->
        <section class="statistic">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <!-- DATA TABLE -->

                        <div class="table-data__tool">

                            <div class="table-data__tool-right">
                                <a href="@Url.Action("AddNew", "Testimonial")" class="au-btn au-btn-icon au-btn--green au-btn--small">
                                    Add New
                                    <i class="zmdi zmdi-plus"></i>
                                </a>
                            </div>
                        </div>
                        <div class="table-responsive table-responsive-data2">
                            <table class="table table-data2">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Person</th>
                                        <th>Designation</th>
                                        <th>Photo</th>
                                        <th>Comment</th>
                                        <th>Sort Index</th>
                                        <th>Comment Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr class="tr-shadow">

                                                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Person)
                                                </td>
                                                <td>@Html.DisplayFor(modelItem => item.Designation)</td>
                                                <td><img src="@item.PhotoPath" /></td>
                                                <td>@Html.Raw(HttpUtility.HtmlDecode(@item.TestimonialText))</td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.SortIndex)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.CommentDateText)
                                                </td>
                                                <td>
                                                    <div class="table-data-feature">
                                                        <button class="item" onclick="location.href='@Url.Action("AddNew", "Testimonial", new { tid = item.Id })';return false;" data-toggle="tooltip" data-placement="top" title="Edit">
                                                            <i class="zmdi zmdi-edit"></i>
                                                        </button>
                                                        <form id="delete-form">
                                                            <input type="hidden" id="tid" name="tid" value="@item.Id" />
                                                            <button type="submit" class="item" id="btnSend" title="Delete"><i class="zmdi zmdi-delete"></i></button>
                                                        </form>
                                                        <button class="item" onclick="location.href='@Url.Action("Details", "Testimonial", new { tid = item.Id })';return false;" data-toggle="tooltip" data-placement="top" title="More">
                                                            <i class="zmdi zmdi-more"></i>
                                                        </button>

                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- END DATA TABLE -->
                    </div>
                </div>
            </div>
            <div id="successModal" class="modal fade" role="dialog">
                <div class="modal-dialog modal-sm">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Response</h4>
                        </div>
                        <div class="modal-body" align="center">
                            <p id="successModalText"></p>
                            <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
        <script>
            $('#btnSend').on('click', function () { //ref from Larssons Contact Form
                if ($("#delete-form").length) {
                    var form = document.getElementById('delete-form');
                    var form_data = new FormData(form);
                    console.log(form_data);
                    $.ajax({
                        type: "POST",
                        url: "/Admin/Testimonial/RemoveList",
                        data: form_data,
                        processData: false,
                        contentType: false,
                        success: function (data) {
                            $('#successModal').modal('show');
                            $('#successModalText').text(data.Message);

                        },
                        error: function () {
                            $('#successModal').modal('show');
                            $('#successModalText').text(error.status + "<--save and--> " + error.statusText);
                        }
                    });
                    return false; // required to block normal submit since you used ajax

                }
            });
        </script>
    </div>