DesiFood/Areas/Admin/Controllers/LanguageController.cs
using CMS.Admin.Facade;
using CMS.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesiFood.Areas.Admin.Controllers
{
    public class LanguageController : Controller
    {
        MiscFacade _misc = new MiscFacade();
        // GET: Admin/Language
        public ActionResult Index()
        {
            var data = _misc.GetAllLanguages();
            return View(data);
        }

        public ActionResult AddNew(long? id)
        {
            if (id != null)
            {
                var data = _misc.LoadLanguage((long)id);
                return View(data);
            }
            else
                return View();
        }
        [HttpPost]
        public JsonResult SaveLanguage(LanguageDto dto)
        {
            var data = _misc.SaveLanguage(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(long id)
        {
            var data = _misc.LoadLanguage((long)id);
            return View(data);
        }
    }
}

DesiFood/Areas/Admin/Views/Language/AddNew.cshtml
@model CMS.Dto.LanguageDto
@{
    ViewBag.Title = "Add New Language";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}
<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Add Language
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">
                                    @Html.ActionLink("Languages", "Index", "Language")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">Add New</li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form id="save_form" enctype="multipart/form-data">
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add Form</strong>
                        </div>
                        <div class="card-body card-block">

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.LanguageName, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.HiddenFor(model => model.Id)
                                </div>
                                <div class="col-12 col-md-9">
                                   
                                    @Html.TextBoxFor(model => model.LanguageName, new { @class = "form-control" })

                                    <small class="form-text text-muted">This is full name</small>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.Label("Icon Image", htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @if (Model != null)
                                    {
                                        <img src="@Model.IconImagepath" width="25%" />
                                    }
                                        <input type="file" id="IconImage" class="form-control-file">
                                        <small class="form-text text-muted">This is flag image</small>
                                    </div>
                            </div>

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.ShortName, new { @class = "form-control" })

                                    <small class="form-text text-muted">This is short name</small>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.DropDownListFor(x => x.Status, EnumHelper.GetSelectList(typeof(CMS.Infrastructure.EntityStatus)), new { @class = "form-control" })
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="button" id="btnSave" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>

                    </div>
                </div>
            </form>
        </div>
    </section>

</div>

<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="smallmodalLabel">Response</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="successModalText"></p>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Confirm</button>*@
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#btnSave').on('click', function () {
        //event.preventDefault();
        var photoFile = $('#IconImage').prop('files')[0];

        var form = document.getElementById('save_form');
     
        var form_data = new FormData(form);
        form_data.append('IconImage', photoFile);
      
        $.ajax({
            type: "POST",
            url: '/Admin/Language/SaveLanguage',
            data: form_data,
            processData: false,
            contentType: false,
            success: function (data) {
                $('#successModal').modal('show');
                $('#successModalText').text(data.Message);

            },
            error: function () {
                $('#successModal').modal('show');
                $('#successModalText').text(error.status + "<--save and--> " + error.statusText);

            }
        });
    });


</script>

DesiFood/Areas/Admin/Views/Language/Details.cshtml
@model CMS.Dto.LanguageDto
@{
    ViewBag.Title = "Language Details";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Language Details
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">More Information</li>

                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <a href='@Url.Action("Index", "Language")'>Back to List</a>
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form>
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Language Details</strong>
                        </div>
                        <div class="card-body card-block">
                            <dl class="dl-horizontal">

                                <dt>
                                    @Html.DisplayNameFor(model => model.LanguageName)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.LanguageName)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.IconImage)
                                </dt>

                                <dd>
                                    
                                    <img src="@Model.IconImagepath" alt="@Model.LanguageName">
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.ShortName)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.ShortName)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.StatusText)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.StatusText)
                                </dd>




                            </dl>

                        </div>
                        <div class="card-footer">
                            <p>
                                <a href='@Url.Action("AddNew", "Language",new { id = Model.Id })'>Edit</a>  |  <a href='@Url.Action("Index", "Language")'>Back to List</a>
                            </p>
                        </div>
                    </div>

                </div>

            </form>

        </div>

    </section>
</div>

DesiFood/Areas/Admin/Views/Language/Index.cshtml
@model IEnumerable<CMS.Dto.LanguageDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        All Languages
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item active">
                                    <a href="#">Home</a>
                                </li>
                                <li class="list-inline-item seprate">
                                    <span>/</span>
                                </li>
                                <li class="list-inline-item">Language</li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END WELCOME-->
    <section class="statistic">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- DATA TABLE -->

                    <div class="table-data__tool">

                        <div class="table-data__tool-right">
                            <a href="@Url.Action("AddNew", "Language")" class="au-btn au-btn-icon au-btn--green au-btn--small">
                                Add Language
                                <i class="zmdi zmdi-plus"></i>
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive table-responsive-data2">
                        <table class="table table-data2">
                            <thead>
                                <tr>

                                    <th>Id</th>
                                    <th>Language Name</th>
                                    <th>Icon </th>
                                    <th>Short Name</th>
                                    <th>Status</th>

                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                <tr class="tr-shadow">

                                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LanguageName)
                                    </td>
                                    <td>
                                        <img src="@item.IconImagepath"  width="25%"/>
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ShortName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.StatusText)
                                    </td>

                                    <td>
                                        <div class="table-data-feature">
                                            <button class="item" onclick="location.href='@Url.Action("AddNew", "Language",new { id = item.Id })';return false;" data-toggle="tooltip" data-placement="top" title="Edit">
                                                <i class="zmdi zmdi-edit"></i>
                                            </button>

                                            <button class="item" onclick="location.href='@Url.Action("Details", "Language",new { id = item.Id })';return false;" data-toggle="tooltip" data-placement="top" title="More">
                                                <i class="zmdi zmdi-more"></i>
                                            </button>

                                        </div>
                                    </td>
                                </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                    <!-- END DATA TABLE -->
                </div>
            </div>
        </div>
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Response</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p id="successModalText"></p>
                        <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
    </section>
    
</div>