DesiFood/Areas/Admin/Controllers/CMSUserController.cs
using CMS.Admin.Facade;
using CMS.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesiFood.Areas.Admin.Controllers
{
    public class CMSUserController : Controller
    {
        // GET: Admin/CMSUser
        AdminUsersFacade _user = new AdminUsersFacade();
        
        public ActionResult Index()
        {
            var data = _user.GetAllUsers();
            return View(data);
        }
        public ActionResult AddNew(long? userid)
        {
            if (userid != null)
            {
                var data = _user.LoadUserInfo((long)userid);
                return View(data);
            }
            else
                return View();
        }

        [HttpPost]
        public JsonResult SaveUser(AdminPanelLoginsDto dto)
        {
            var data = _user.SaveAdminUser(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult RemoveUser(long userid)
        {
            var data = _user.DeleteUser(userid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(long userid)
        {
            var data = _user.LoadUserInfo((long)userid);
            return View(data);
        }
    }
}

DesiFood/Areas/Admin/Views/CMSUser/AddNew.cshtml
@model CMS.Dto.AdminPanelLoginsDto
@{
    ViewBag.Title = "Add New User";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Add CMS User
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">
                                    @Html.ActionLink("Users", "Index", "CMSUser")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">Add New</li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Back to List", "Index")
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form id="save_form">
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add User</strong>
                        </div>
                        <div class="card-body card-block">

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.UN_1, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.HiddenFor(model => model.Id)
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.UN_1, new { @class = "form-control" })

                                    <small class="form-text text-muted">This is user name</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.PS_1, htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.PS_1, "Password", new { @class = "form-control", @type = "password" })

                                    <small class="form-text text-muted">set the password</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @type = "email" })

                                    <small class="form-text text-muted">test@fsdjf.com</small>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.DropDownListFor(x => x.Role, EnumHelper.GetSelectList(typeof(CMS.Infrastructure.RoleEnum)), new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "form-control-label" })

                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.DropDownListFor(x => x.Status, EnumHelper.GetSelectList(typeof(CMS.Infrastructure.EntityStatus)), new { @class = "form-control" })
                                </div>
                            </div>
                        </div>


                        


                    </div>
                    <div class="card-footer">
                        <button type="button" id="btnSave" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>

                    </div>
                </div>
            </form>
        </div>
    </section>

</div>

<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="smallmodalLabel">Response</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="successModalText"></p>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Confirm</button>*@
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#btnSave').on('click', function () {
        //event.preventDefault();
        var form = document.getElementById('save_form');
        var form_data = new FormData(form);
        $.ajax({
            type: "POST",
            url: '/Admin/CMSUser/SaveUser',
            data: form_data,
            processData: false,
            contentType: false,
            success: function (data) {
                $('#successModal').modal('show');
                $('#successModalText').text(data.Message);

            },
            error: function () {
                $('#successModal').modal('show');
                $('#successModalText').text(error.status + "<--save and--> " + error.statusText);

            }
        });
    });


</script>

DesiFood/Areas/Admin/Views/CMSUser/Details.cshtml
@model CMS.Dto.AdminPanelLoginsDto
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        User Details
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">More Information</li>

                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <a href='@Url.Action("Index", "CMSUser")'>Back to List</a>
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form>
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>User Details</strong>
                        </div>
                        <div class="card-body card-block">
                            <dl class="dl-horizontal">

                                <dt>
                                    @Html.DisplayNameFor(model => model.UN_1)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.UN_1)
                                </dd>


                                <dt>
                                    @Html.DisplayNameFor(model => model.Role)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Role)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Status)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.StatusText)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.LastUpdate)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.LastUpdateText)
                                </dd>


                            </dl>

                        </div>
                        <div class="card-footer">
                            <p>
                                <a href='@Url.Action("AddNew", "CMSUser",new { userid = Model.Id })'>Edit</a>  |  <a href='@Url.Action("Index", "CMSUser")'>Back to List</a>
                            </p>
                        </div>
                    </div>

                </div>

            </form>

        </div>

    </section>
</div>

DesiFood/Areas/Admin/Views/CMSUser/Index.cshtml
@model IEnumerable<CMS.Dto.AdminPanelLoginsDto>
@{
    ViewBag.Title = "Admin Users";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

    <div class="page-content--bgf7 main-content">

        <!-- END BREADCRUMB-->
        <!-- WELCOME-->
        <section class="welcome p-t-10">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="title-4">
                            CMS Users
                        </h1>
                        <hr class="line-seprate">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="au-breadcrumb-content">
                            <div class="au-breadcrumb-left">
                                <span class="au-breadcrumb-span">You are here:</span>
                                <ul class="list-unstyled list-inline au-breadcrumb__list">
                                    <li class="list-inline-item active">
                                        <a href="#">Home</a>
                                    </li>
                                    <li class="list-inline-item seprate">
                                        <span>/</span>
                                    </li>
                                    <li class="list-inline-item">CMS USers</li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- END WELCOME-->
        <section class="statistic">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <!-- DATA TABLE -->

                        <div class="table-data__tool">

                            <div class="table-data__tool-right">
                                <a href="@Url.Action("AddNew", "CMSUser")" class="au-btn au-btn-icon au-btn--green au-btn--small">
                                    Add User
                                    <i class="zmdi zmdi-plus"></i>
                                </a>
                            </div>
                        </div>
                        <div class="table-responsive table-responsive-data2">
                            <table class="table table-data2">
                                <thead>
                                    <tr>

                                        <th>Id</th>
                                        <th>User Name</th>
                                        <th>Role</th>
                                        <th>Email</th>
                                        <th>Status</th>
                                       
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        foreach (var item in Model)
                                        {
                                    <tr class="tr-shadow">

                                        <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.UN_1)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Role)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StatusText)
                                        </td>

                                        <td>
                                            <div class="table-data-feature">
                                                <button class="item" onclick="location.href='@Url.Action("AddNew", "CMSUser",new { userid = item.Id })';return false;" data-toggle="tooltip" data-placement="top" title="Edit">
                                                    <i class="zmdi zmdi-edit"></i>
                                                </button>
                                                <button onclick="DeleteUser(@item.Id)" class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                                    <i class="zmdi zmdi-delete"></i>
                                                </button>

                                                <button class="item" onclick="location.href='@Url.Action("Details", "CMSUser",new { userid = item.Id })';return false;" data-toggle="tooltip" data-placement="top" title="More">
                                                    <i class="zmdi zmdi-more"></i>
                                                </button>

                                            </div>
                                        </td>
                                    </tr>
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                        <!-- END DATA TABLE -->
                    </div>
                </div>
            </div>
            <div id="successModal" class="modal fade" role="dialog">
                <div class="modal-dialog modal-sm">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Response</h4>
                        </div>
                        <div class="modal-body" align="center">
                            <p id="successModalText"></p>
                            <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <script>
        DeleteUser = function (id) {
            //var element = $(this);
            //var id = element.attr("id");

            console.log(id);
            $.ajax({
                type: "POST",
                url: '/Admin/CMSUser/RemoveUser',
                data: { userid:id},
                DataType: 'json',
                success: function (data) {
                    $('#successModal').modal('show');
                    $('#successModalText').text(data.Message);

                },
                error: function () {
                    $('#successModal').modal('show');
                    $('#successModalText').text(error.status + "<--save and--> " + error.statusText);

                }
            });
        }


        </script>
    </div>