DesiFood/Areas/Admin/Controllers/CategoryController.cs
using CMS.Admin.Facade;
using CMS.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesiFood.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        ProductFacade _prod = new ProductFacade();
        BranchFacade _brance = new BranchFacade();
        MiscFacade _misc = new MiscFacade();
        // GET: Admin/Category
        public ActionResult Index()
        {
            var data = _prod.GetAllCategory();
            return View(data);
        }

        public ActionResult AddNew(long? cid, int? level = 0)
        {
            var categories = _prod.GetAllCategory().Where(x => (int)x.CatLevel == level).ToList();
            categories.Insert(0, null);

            ViewBag.Parents = categories;
            if (cid != null)
            {
                var data = _prod.LoadCategory((long)cid);
                return View(data);
            }
            else
                return View();
        }

        public ActionResult Details(long cid)
        {
            var data = _prod.LoadCategory((long)cid);
            return View(data);
        }

        [HttpPost]
        public JsonResult SaveCategory(ProductCategoryDto dto)
        {
            var data = _prod.SaveCategory(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult RemoveCategory(long cid)
        {
            var data = _prod.DeleteCategory(cid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }




        public ActionResult AddNewContent(long? cid, long? cdid)
        {
            if (cdid != null)
            {
                var data = _prod.LoadCategoryContentDetails((long)cdid);
                return View(data);
            }
            else
            {
                ViewBag.CategoryId = cid;
                ViewBag.CategoryName = _prod.LoadCategory((long)cid).CategoryName;
                return View();
            }

        }

        public ActionResult CategoryDetails(long cdid)
        {
            var data = _prod.LoadCategoryContentDetails((long)cdid);
            return View(data);
        }

        [HttpPost]
        public JsonResult SaveContent(CategoryDetailDto dto)
        {
            var data = _prod.SaveCategoryContent(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

DesiFood/Areas/Admin/Controllers/SettingsController.cs
using CMS.Admin.Facade;
using CMS.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesiFood.Areas.Admin.Controllers
{
    public class SettingsController : Controller
    {
        TagFacade _category = new TagFacade();
        MiscFacade _misc = new MiscFacade();
        // GET: Admin/Category
        #region Tags
        public ActionResult BlogTags()
        {
            var data = _category.GetAllTags(CMS.Infrastructure.TagType.Blog);
            return View(data);
        }

        public ActionResult MenuTags()
        {
            var data = _category.GetAllTags(CMS.Infrastructure.TagType.Menu);
            return View(data);
        }

        public ActionResult AddNew(long? tid)
        {
            if (tid != null)
            {
                var data = _category.LoadTag((long)tid);
                return View(data);
            }
            else
                return View();
        }

        [HttpPost]
        public JsonResult SaveTag(TagDto dto)
        {
            var data = _category.SaveTag(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult RemoveTag(long id)
        {
            var data = _category.DeleteTag(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(long tid)
        {
            var data = _category.LoadTag((long)tid);
            return View(data);
        } 
        #endregion

        #region Contact Subjects
        public ActionResult ContactSubjects()
        {
            var data = _misc.GetAllContactSubjects();
            return View(data);
        }

        public ActionResult AddNewSubject(long? subid)
        {
            var languages = _misc.GetAllLanguages();

            ViewBag.Languages = from s in languages
                                select new { Id = s.Id, LanguageName = s.ShortName };
            if (subid != null)
            {
                var data = _misc.LoadContactSubject((long)subid);
                return View(data);
            }
            else
                return View();
        }
        [HttpPost]
        public JsonResult SaveSubject(ContactSubjectDto dto)
        {
            var data = _misc.SaveContactSubject(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult RemoveSubject(long subid)
        {
            var data = _misc.DeleteSubject(subid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SubjectDetails(long subid)
        {
            var data = _misc.LoadContactSubject((long)subid);
            return View(data);
        }
        #endregion

        #region Content Types
        public ActionResult ContactTypes()
        {
            var data = _misc.GetAllContentTypes("");
            return View(data);
        }

        public ActionResult AddContentType(long? contid)
        {
            if (contid != null)
            {
                var data = _misc.LoadContentType((long)contid);
                return View(data);
            }
            else
                return View();
        }
        [HttpPost]
        public JsonResult SaveContentType(ContentTypeDto dto)
        {
            var data = _misc.SaveContentType(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult RemoveContentType(long contid)
        {
            var data = _misc.DeleteContentType(contid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ContentTypeDetails(long contid)
        {
            var data = _misc.LoadContentType((long)contid);
            return View(data);
        }
        #endregion

        #region UoMs
        public ActionResult UoMs()
        {
            var data = _misc.GetAllUoMs();
            return View(data);
        }
        [HttpGet]
        public string UoMsJQ()
        {
            var data = _misc.GetAllUoMs();
            string strret = "<select>";
            foreach (UoMDto item in data)
            {
                strret += "<option value='" + item.Id + "'>" + item.Name + "</option>";
            }
            strret += "</select>";
            return strret;
        }
        public ActionResult AddNewUoM(long? oid)
        {
            if (oid != null)
            {
                var data = _misc.LoadUoM((long)oid);
                return View(data);
            }
            else
                return View();
        }
        [HttpPost]
        public JsonResult SaveUoM(UoMDto dto)
        {
            var data = _misc.SaveUoM(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult RemoveUoM(long oid)
        {
            var data = _misc.DeleteUoM(oid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UoMDetails(long oid)
        {
            var data = _misc.LoadUoM((long)oid);
            return View(data);
        } 
        #endregion
    }
}

DesiFood/Areas/Admin/Views/Settings/AddNew.cshtml
@model CMS.Dto.TagDto

@{
    ViewBag.Title = "New Tag";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content--bgf7 main-content">
    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Add Tag
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">
                                    @Html.ActionLink("All Tags", "BlogTags", "Settings")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">Add New</li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Back to List", "BlogTags")
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form id="save_form">
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add Form</strong>
                        </div>
                        <div class="card-body card-block">

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Tag1, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.HiddenFor(model => model.Id)
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.Tag1, new { @class = "form-control" })

                                    <small class="form-text text-muted">This is tag</small>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "form-control-label" })
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.DropDownListFor(x => x.Type, EnumHelper.GetSelectList(typeof(CMS.Infrastructure.TagType)), new { @class = "form-control" })
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="button" id="btnSave" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>

                    </div>
                </div>
            </form>
        </div>
    </section>
</div>

<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="smallmodalLabel">Response</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="successModalText"></p>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Confirm</button>*@
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#btnSave').on('click', function () {
        //event.preventDefault();
        var form = document.getElementById('save_form');
        var form_data = new FormData(form);
        $.ajax({
            type: "POST",
            url: '/Admin/Settings/SaveTag',
            data: form_data,
            processData: false,
            contentType: false,
            success: function (data) {
                $('#successModal').modal('show');
                $('#successModalText').text(data.Message);

            },
            error: function () {
                $('#successModal').modal('show');
                $('#successModalText').text(error.status + "<--save and--> " + error.statusText);

            }
        });
    });
</script>

DesiFood/Areas/Admin/Views/Settings/AddNewSubject.cshtml
@model CMS.Dto.ContactSubjectDto
@{
    ViewBag.Title = "Add New Subject";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Add Contact Subjects
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">
                                    @Html.ActionLink("Contact Subjects", "ContactSubjects", "Category")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">Add New</li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Back to List", "ContactSubjects")
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form id="save_form">
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add Form</strong>
                        </div>
                        <div class="card-body card-block">

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.HiddenFor(model => model.Id)
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.Subject, new { @class = "form-control" })

                                    <small class="form-text text-muted">This is title of Subject</small>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.LangId, "Language", htmlAttributes: new { @class = "form-control-label" })
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.DropDownListFor(x => x.LangId, new SelectList(ViewBag.Languages, "Id", "LanguageName"), new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="button" id="btnSave" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>

                    </div>
                </div>
            </form>
        </div>
    </section>

</div>

<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="smallmodalLabel">Response</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="successModalText"></p>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Confirm</button>*@
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#btnSave').on('click', function () {
        //event.preventDefault();
        var form = document.getElementById('save_form');
        var form_data = new FormData(form);
        $.ajax({
            type: "POST",
            url: '/Admin/Settings/SaveSubject',
            data: form_data,
            processData: false,
            contentType: false,
            success: function (data) {
                $('#successModal').modal('show');
                $('#successModalText').text(data.Message);

            },
            error: function () {
                $('#successModal').modal('show');
                $('#successModalText').text(error.status + "<--save and--> " + error.statusText);

            }
        });
    });


</script>

DesiFood/Areas/Admin/Views/Settings/AddNewUoM.cshtml
@model CMS.Dto.UoMDto
@{
    ViewBag.Title = "Add New UoM";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Add Unit of Measurement
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>

                                <li class="list-inline-item">Add New</li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.ActionLink("Back to List", "UoMs","Settings")
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form id="save_form">
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Add Form</strong>
                        </div>
                        <div class="card-body card-block">

                            <div class="row form-group">
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-control-label" })
                                    @Html.HiddenFor(model => model.Id)
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })

                                    <small class="form-text text-muted">This is name</small>
                                </div>
                                <div class="col col-md-3">
                                    @Html.LabelFor(model => model.ShortName, htmlAttributes: new { @class = "form-control-label" })
                                    
                                </div>
                                <div class="col-12 col-md-9">
                                    @Html.TextBoxFor(model => model.ShortName, new { @class = "form-control" })

                                    <small class="form-text text-muted">This is short name</small>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="button" id="btnSave" class="btn btn-primary btn-sm">
                            <i class="fa fa-dot-circle-o"></i> Submit
                        </button>

                    </div>
                </div>
            </form>
        </div>
    </section>

</div>

<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="smallmodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="smallmodalLabel">Response</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id="successModalText"></p>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Confirm</button>*@
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#btnSave').on('click', function () {
        //event.preventDefault();
        var form = document.getElementById('save_form');
        var form_data = new FormData(form);
        $.ajax({
            type: "POST",
            url: '/Admin/Settings/SaveUoM',
            data: form_data,
            processData: false,
            contentType: false,
            success: function (data) {
                $('#successModal').modal('show');
                $('#successModalText').text(data.Message);

            },
            error: function () {
                $('#successModal').modal('show');
                $('#successModalText').text(error.status + "<--save and--> " + error.statusText);

            }
        });
    });


</script>

DesiFood/Areas/Admin/Views/Settings/ContentTypeDetails.cshtml
@model CMS.Dto.ContentTypeDto
@{
    ViewBag.Title = "ContentTypeDetails";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="page-content--bgf7 main-content">
    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Content Type Details
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">More Information</li>

                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <a href='@Url.Action("ContactTypes", "Settings")'>Back to List</a>
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form>
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong> Details</strong>
                        </div>
                        <div class="card-body card-block">
                            <dl class="dl-horizontal">

                                <dt>
                                    @Html.DisplayName("Type Name")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Category)
                                </dd>

                                <dt>
                                    @Html.DisplayName("Last Update")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.LastUpdateText)
                                </dd>


                            </dl>

                        </div>



                        <div class="card-footer">
                            <p>
                                <a href='@Url.Action("AddContentType", "Settings",new { contid = Model.Id })'>Edit</a>  |  <a href='@Url.Action("ContactTypes", "Settings")'>Back to List</a>
                            </p>
                        </div>
                    </div>

                </div>

            </form>

        </div>

    </section>
</div>

DesiFood/Areas/Admin/Views/Settings/Details.cshtml
@model CMS.Dto.TagDto

@{
    ViewBag.Title = "Tag Details";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        Tag Details
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">More Information</li>

                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <a href='@Url.Action("BlogTags", "Settings")'>Back to List</a>
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form>
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Tag Details</strong>
                        </div>
                        <div class="card-body card-block">
                            <dl class="dl-horizontal">
                                
                                <dt>
                                    @Html.DisplayName("Tag Name")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Tag1)
                                </dd>


                                <dt>
                                    @Html.DisplayName("Tag Type")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.TypeName)
                                </dd>

                            </dl>

                        </div>
                        <div class="card-footer">
                            <p>
                                <a href='@Url.Action("AddNew", "Settings",new { tid = Model.Id })'>Edit</a>  |  <a href='@Url.Action("BlogTags", "Settings")'>Back to List</a>
                            </p>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
</div>